
from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors

def build_pdf_bytes(data):
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=36, rightMargin=36, topMargin=36, bottomMargin=36)
    styles = getSampleStyleSheet()
    story = []

    title = data.get("report_title", "Prime Credit Reference Bureau")
    subtitle = data.get("report_subtitle", "Individual Credit Report")
    story.append(Paragraph(title, styles['Title']))
    story.append(Paragraph(subtitle, styles['Heading2']))
    story.append(Spacer(1, 12))

    fields = [
        ("Full Name", "Full_Name"),
        ("Date of Birth", "Date_of_Birth"),
        ("National ID", "National_ID"),
        ("Current Address", "Current_Address"),
        ("Phone Number", "Phone_Number"),
        ("Employment", "Employment"),
        ("Employer", "Employer"),
        ("Income Level", "Income_Level"),
        ("Credit Score (FICO Model)", "Credit_Score"),
        ("Score Range", "Score_Range"),
        ("Score Category", "Score_Category"),
        ("Credit Utilization Ratio", "Credit_Utilization_Ratio"),
        ("Payment History Score", "Payment_History_Score"),
        ("Debt-to-Income Ratio", "Debt_to_Income_Ratio"),
        ("Open Credit Lines", "Open_Credit_Lines"),
        ("Past Due Accounts", "Past_Due_Accounts"),
        ("Length of Credit History", "Length_of_Credit_History"),
        ("Recent Credit Inquiries", "Recent_Credit_Inquiries"),
        ("Collateral Provided", "Collateral_Provided"),
        ("Account Types", "Account_Types"),
        ("Macroeconomic Risk Adjustment", "Macroeconomic_Risk_Adjustment"),
    ]

    table_data = [["Attribute", "Value"]]
    for label, key in fields:
        table_data.append([label, str(data.get(key, ""))])

    table = Table(table_data, colWidths=[200, 320])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#f0f0f0")),
        ('TEXTCOLOR', (0,0), (-1,0), colors.black),
        ('GRID', (0,0), (-1,-1), 0.25, colors.grey),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('ALIGN', (0,0), (-1,0), 'LEFT'),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('LEFTPADDING', (0,0), (-1,-1), 6),
        ('RIGHTPADDING', (0,0), (-1,-1), 6),
        ('TOPPADDING', (0,0), (-1,-1), 4),
        ('BOTTOMPADDING', (0,0), (-1,-1), 4),
    ]))

    story.append(table)
    story.append(Spacer(1, 18))
    story.append(Paragraph("Generated by Prime Credit Reference Bureau System", styles['Italic']))

    doc.build(story)
    buf.seek(0)
    return buf
